server:
  port:  4000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_spring_boot
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jwt:
    signerKey: dfadfa
    valid-duration: 3600


