server: 
   port: 4000
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/java_spring_boot
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:            
            show-sql: true
            ddl-auto: update
jwt:
    keys: 3YjW35WxwwJHXS7NiQsNrdeilhj2wyqp5qcHmJlOeGLrVOoms6wcqvqP161tF2SC
    